AWSTemplateFormatVersion: '2010-09-09'
Description: >
  This CloudFormation template spins up an S3 bucket

Parameters:
  CircleCiWorkflowId:
    Description: The CircleCI ID for the current workflow
    Type: String
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String

Resources:
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "udacity-cdn-promote-to-production-${CircleCiWorkflowId}"
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html

  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref 'WebsiteBucket'
      PolicyDocument:
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: s3:GetObject
            Resource: !Join ['', ['arn:aws:s3:::', !Ref 'WebsiteBucket', /*]]

Outputs:
  CircleCiWorkflowId:
    Value: !Sub "${CircleCiWorkflowId}"
    Export:
      Name: !Sub "CircleCiId-${CircleCiWorkflowId}"